// gen-versions reads deploy/versions.conf and generates a Go file with typed
// constants for use in the config package.
//
// Usage:
//
//	go run cmd/gen-versions/main.go -input <versions.conf> -output <versions_gen.go>
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

// nameMap translates KEY names from versions.conf to Go constant names.
var nameMap = map[string]string{
	"IMAGE_REGISTRY":      "DefaultImageRegistry",
	"IMAGE_VERSION_API":   "DefaultAPIVersion",
	"IMAGE_VERSION_UI":    "DefaultUIVersion",
	"IMAGE_VERSION_ROUTER":  "DefaultRouterVersion",
	"IMAGE_VERSION_GATEWAY": "DefaultGatewayVersion",
	"IMAGE_VERSION_GITEA":   "DefaultGiteaVersion",
}

// orderedKeys preserves declaration order from versions.conf so the generated
// file is deterministic and matches the canonical key order.
var orderedKeys = []string{
	"IMAGE_REGISTRY",
	"IMAGE_VERSION_API",
	"IMAGE_VERSION_UI",
	"IMAGE_VERSION_ROUTER",
	"IMAGE_VERSION_GATEWAY",
	"IMAGE_VERSION_GITEA",
}

func main() {
	input := flag.String("input", "", "path to versions.conf")
	output := flag.String("output", "", "path to generated Go file")
	flag.Parse()

	if *input == "" || *output == "" {
		flag.Usage()
		os.Exit(1)
	}

	values, err := parseVersions(*input)
	if err != nil {
		log.Fatalf("parse %s: %v", *input, err)
	}

	src, err := generate(values)
	if err != nil {
		log.Fatalf("generate: %v", err)
	}

	if err := os.WriteFile(*output, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", *output, err)
	}
}

// parseVersions reads a shell KEY=VALUE file, skipping blank lines and
// comments (lines starting with #).
func parseVersions(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	values := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		values[key] = val
	}
	return values, scanner.Err()
}

// generate produces a gofmt-formatted Go source file containing the version
// constants.
func generate(values map[string]string) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "// Code generated by gen-versions. DO NOT EDIT.")
	fmt.Fprintln(&buf, "package config")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "const (")

	// Compute the longest constant name for alignment.
	maxLen := 0
	for _, key := range orderedKeys {
		if constName, ok := nameMap[key]; ok {
			if _, hasVal := values[key]; hasVal {
				if len(constName) > maxLen {
					maxLen = len(constName)
				}
			}
		}
	}

	for _, key := range orderedKeys {
		constName, ok := nameMap[key]
		if !ok {
			continue
		}
		val, hasVal := values[key]
		if !hasVal {
			continue
		}
		padding := strings.Repeat(" ", maxLen-len(constName))
		fmt.Fprintf(&buf, "\t%s%s = %q\n", constName, padding, val)
	}

	fmt.Fprintln(&buf, ")")

	return format.Source(buf.Bytes())
}
