controller:
  replicaCount: 1

  ingressClass: nginx

  ingressClassResource:
    name: nginx
    default: true

  config:
    enable-real-ip: "true"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

    worker-processes: "auto"
    max-worker-connections: "30000"

    proxy-body-size: 50m
    keep-alive: "300"
    keep-alive-requests: "65535"

    ssl-redirect: "false"

    log-format-escape-json: "true"
    log-format-upstream: |
      { "time": "$time_iso8601",
        "remote_addr": "$remote_addr",
        "x-forward-for": "$proxy_add_x_forwarded_for",
        "request_id": "$request_id",
        "status": $status,
        "host": "$host",
        "path": "$uri",
        "method": "$request_method",
        "request_time": $request_time,
        "upstream_addr": "$upstream_addr"
      }

  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
