package engine

import (
	"context"
	"fmt"
	"os"
	"time"
)

const dnsmasqConfDir = "/etc/dnsmasq.d"
const dnsmasqConfFile = "/etc/dnsmasq.d/launchpad.conf"

func (e *Engine) configureDnsmasq(ctx context.Context) error {
	// Only configure if dnsmasq is available
	if _, err := RunWithOutput(ctx, "check-dnsmasq", 5*time.Second, "which", "dnsmasq"); err != nil {
		return nil // dnsmasq not installed, skip silently
	}

	hostIP := detectHostIP()
	domain := e.cfg.Domain

	if err := os.MkdirAll(dnsmasqConfDir, 0755); err != nil {
		return fmt.Errorf("creating dnsmasq config dir: %w", err)
	}

	projectDomain := e.cfg.ResolvedProjectDomain()
	addressLines := fmt.Sprintf("address=/%s/%s", domain, hostIP)
	if projectDomain != domain {
		addressLines += fmt.Sprintf("\naddress=/%s/%s", projectDomain, hostIP)
	}

	conf := fmt.Sprintf(`# Auto-generated by launchpad deploy — do not edit
# Route *.%s to host IP so Docker containers reach nginx:443
%s
server=223.5.5.5
server=8.8.8.8
`, domain, addressLines)

	if err := os.WriteFile(dnsmasqConfFile, []byte(conf), 0644); err != nil {
		return fmt.Errorf("writing dnsmasq config: %w", err)
	}

	RunWithTimeout(ctx, "restart-dnsmasq", 10*time.Second, "systemctl", "restart", "dnsmasq")

	return nil
}

// RemoveDnsmasq removes the launchpad dnsmasq config and restarts the service.
func RemoveDnsmasq() error {
	if err := os.Remove(dnsmasqConfFile); err != nil && !os.IsNotExist(err) {
		return err
	}
	// Best-effort restart
	_ = RunWithTimeout(context.Background(), "restart-dnsmasq", 10*time.Second, "systemctl", "restart", "dnsmasq")
	return nil
}
