// Code generated by gen-versions. DO NOT EDIT.
package config

const (
	DefaultImageRegistry  = "swr.ap-southeast-1.myhuaweicloud.com/ghisha"
	DefaultAPIVersion     = "2.1.6"
	DefaultUIVersion      = "2.1.5"
	DefaultRouterVersion  = "1.16.2"
	DefaultGatewayVersion = "1.18.7"
	DefaultGiteaVersion   = "1.25-rootless"
)
